services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "brain_user"     
      POSTGRES_PASSWORD: "brain@2025"
      POSTGRES_DB: "agriculture"       
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"                     
    restart: on-failure                
    networks:
      - agnetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_nestjs
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: brain_user
      DB_PASSWORD: brain@2025
      DB_DATABASE: agriculture
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - agnetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_react
    restart: always
    depends_on:
      - backend
    ports:
      - "4000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - agnetwork

volumes:
  postgres_data:

networks:
  agnetwork:
    driver: bridge
